# Generated by Django 5.1.1 on 2024-09-28 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='chapter_progress',
        ),
    ]
